In [2]:
import qgrid
import pandas as pd
import dtale

# qgrid.set_defaults(export_mode=True, show_toolbar=True)

In [232]:
file = 'new_output.xlsx'
df = pd.read_excel(file)

# df = df.round(decimals=3)

# df.style.set_sticky(axis="columns")
# df = df[~df['Unnamed: 0']]

df = df.loc[:, ~df.columns.str.contains('^Unnamed')]


df.head()

,Season Rank,Z-Score,Player,Team,Season,p/g,3/g,r/g,a/g,s/g,b/g,fg%,ft%,to/g
0,1,1.46,"Bird, Larry",BOS,86-87,28.1,1.22,9.2,7.6,1.82,0.95,0.525,0.910,3.2
1,1,1.45,"Bird, Larry",BOS,87-88,29.9,1.29,9.3,6.1,1.64,0.75,0.527,0.916,2.8
2,2,1.40,"Jordan, Michael",CHI,87-88,35.0,0.09,5.5,5.9,3.16,1.60,0.535,0.841,3.1
3,1,1.36,"Bird, Larry",BOS,84-85,28.7,0.70,10.5,6.6,1.61,1.23,0.522,0.882,3.1
4,1,1.35,"Jordan, Michael",CHI,88-89,32.5,0.33,8.0,8.0,2.89,0.80,0.538,0.850,3.6

In [233]:
columns = ['Z-Score', 'p/g', 
           '3/g', 'a/g', 'r/g',
          's/g', 'b/g', 'to/g',
          'ft%', 'fg%']

df_values = df[columns]
df_names = df.drop(columns, axis=1)

# for column in df.columns:
#     if column in columns:
#         df[column] = df[column].map('{:.2f}'.format)

# widget = qgrid.show_grid(df)
# qgrid.show_grid(df)
# dtale.show(df)

df_names.head()

# type(df.iloc[0]['p/g'])

   Season Rank           Player Team Season
0            1      Bird, Larry  BOS  86-87
1            1      Bird, Larry  BOS  87-88
2            2  Jordan, Michael  CHI  87-88
3            1      Bird, Larry  BOS  84-85
4            1  Jordan, Michael  CHI  88-89

In [234]:
# import matplotlib.pyplot as plt  
# from matplotlib import colors

# def b_g(s, cmap='PuBu', low=0, high=0):
#     # Pass the columns from Dataframe A
#     print(s.name)

#     if s.name in columns:
#         a = df.loc[:,s.name].copy()
#         rng = a.max() - a.min()
#         norm = colors.Normalize(a.min() - (rng * low),
#                             a.max() + (rng * high))
#         normed = norm(a.values)
#         c = [colors.rgb2hex(x) for x in plt.cm.get_cmap(cmap)(normed)]
#         return ['background-color: %s' % color for color in c]
#     else:
#         return []


def magnify():
    return [dict(selector="th",
                 props=[("font-size", "4pt")]),
            dict(selector="td",
                 props=[('padding', "0em 0em")]),
            dict(selector="th:hover",
                 props=[("font-size", "12pt")]),
            dict(selector="tr:hover td:hover",
                 props=[('max-width', '200px'),
                        ('font-size', '12pt')])
]

cell_hover = {  # for row hover use <tr> instead of <td>
    'selector': 'tr:hover',
    'props': [('background-color', '#ffffb3')]
}
index_names = {
    'selector': '.index_name',
    'props': 'font-style: italic; color: darkgrey; font-weight:normal;'
}
headers = {
    'selector': 'th:not(.index_name)',
    'props': 'background-color: #000066; color: white;'
}

color = {'ATL':'#CC092F',
        'BOS':'#008853',
        'BKN':'#000000',
        'CHA':'#1D8CAB',
        'CHI':'#BC032B',
        'CLE':'#860038',
        'DAL':'#1061AC',
        'DEN':'#FDB827',
        'DET':'#ED174C',
        'GSW':'#006BB6',
        'HOU':'#D31145',
        'IND':'#002D62',
        'LAC':'#D81D47',
        'LAL':'#FDB827',
        'MEM':'#23375B',
        'MIA':'#BF2F38',
        'MIL':'#00461B',
        'MIN':'#005183',
        'NOR':'#002A5C',
        'NYK':'#F48328',
        'OKC':'#1E3160',
        'ORL':'#0075BD',
        'PHI':'#003DA5',
        'PHO':'#27235C',
        'POR':'#E13A3E',
        'SAC':'#724C9F',
        'SAS':'#84888B',
        'TOR':'#BE0F34',
        'UTA':'#0C2340',
        'WAS':'#E51837',
        'CHH':'#1D8CAB',
        'SEA':'#00653A',
        'SDC':'#D81D47',
        'NJN':'#C6CFD4',
        'WA1':'#E51837',
        'VAN':'#23375B',
        'KCK':'#724C9F'}

def color_team(s):
    return ['background-color: ' + color[s['Team']]]

In [235]:
cmap = 'RdYlGn'
# c1 = {:'{:.2f}'}
f = {'p/g':'{:.2f}'}

styled_table = df.style\
    .set_table_styles([cell_hover], overwrite=False)\
    .background_gradient(cmap=cmap, subset=[columns[1]])\
    .background_gradient(cmap=cmap, subset=[columns[2]])\
    .background_gradient(cmap=cmap, subset=[columns[3]])\
    .background_gradient(cmap=cmap, subset=[columns[4]])\
    .background_gradient(cmap=cmap, subset=[columns[5]])\
    .background_gradient(cmap=cmap, subset=[columns[6]])\
    .background_gradient(cmap=cmap, subset=[columns[7]])\
    .background_gradient(cmap=cmap, subset=[columns[8]])\
    .background_gradient(cmap=cmap, subset=[columns[9]])\
    .background_gradient(cmap='Pastel1', subset=['Z-Score'])\
    .set_sticky(axis="columns")\
    .bar(subset=['Season Rank'], color='#457EAC')\
    .format(precision=2)\
    .set_properties(**{'font-size': '16pt'})\
    .apply(color_team, subset=['Team'], axis=1)\
    .set_properties(**{'color': 'white'}, subset=['Team'])\
    .set_caption("Best Fantasy Players Since 1979/80")\
    .set_table_styles([dict(selector="caption", props=[("font-size", "200%"),
                                                       ("font-weight", "bold")])], overwrite=False)\
    .set_table_styles([{'selector': 'th', 'props': [('font-size', '16pt'),
                                                    ("font-weight", "bold"),
                                                    ("background-color", "white")]}], overwrite=False)\




html = styled_table.to_html(doctype_html=True)

with open("random.html", 'w') as f:
    f.write(html)